server:
  port: 8090

spring:
  application:
    name: springcloud_config  #仓库名称
  cloud:
    config:
      server:
        git:
          #git仓库的访问地址，去掉后缀.git
          uri: https://github.com/tanghu1999/springcloud_config
          search-paths: /**  # 指定搜索根路径下的所有目录，若有多个路径使用逗号隔开


